### PR TITLE
Support proc macro test dependencies

### PR DESCRIPTION
**Pull request by bjorn3**
Fixes https://github.com/oli-obk/ui_test/issues/203

### CODE REVIEW

**Comment by oli-obk** [comment]
Should be able to test this by adding serde_derive and using it in a `//@run` test

**Comment by bjorn3** [comment]
Done. Also fixed the formatting and added two commits to remove the diffs from automatic blessing of all tests.

**Comment by bjorn3** [comment]
Rebased

**Comment by bjorn3** [comment]
Removed an unnecessary change. I don't understand why the last CI run only failed on Windows: https://github.com/oli-obk/ui_test/actions/runs/8216901979/job/22472040330

**Comment by oli-obk** [comment]
> Removed an unnecessary change. I don't understand why the last CI run only failed on Windows: https://github.com/oli-obk/ui_test/actions/runs/8216901979/job/22472040330

I think that may be an orthogonal bug that just didn't surface before. Ralf reported it in miri recently

**Comment by oli-obk** [comment]
It was two bugs! 😆 works locally on windows now. Let's see what CI says

**Comment by oli-obk** [comment]
ah well, now I broke unixes 💀

**Pull request merged**
